version: '3'
services:
  back:
    build: ./back
    ports:
      - 3001:3001
    volumes:
      - ./back:/app/drawingstationbeta-back
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE = drawingstationbeta
    volumes:
      - ./db:/app/drawingstationbeta-db