version: '3'
services:
  back:
    build: ./back
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./back:/app/drawingstationbeta-back
    depends_on:
      - db
  db:
    image: mysql:8.0.23
    container_name: drawing_station_beta_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
  front:
    build: ./front
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./front:/app/drawingstationbeta-front
    depends_on:
      - back